### PR TITLE
Fix linker issues with Rust 1.87

### LINKED ISSUE #76: Bug: tracelogging build broken with rustc 1.87
More details - https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/264#issuecomment-2887305859

--clip

ok Rust 1.87 release details seems to have the reason - https://releases.rs/docs/1.87.0/

[Windows: The standard library no longer links advapi32, except on win7.](https://github.com/rust-lang/rust/pull/138233) Code such as C libraries that were relying on this assumption may need to explicitly link advapi32.

Looks like we need to explicitly link this library in build.rs? Ideally it should be taken care by crates which make direct ETW calls i.e, tracelogging/tracelogging_dynamic crates, but we can add it as temporary workaround for the fix:

fn main() {
    println!("cargo:rustc-link-lib=advapi32");
}

### PR DESCRIPTION
**Pull request by Robo210**
Fixes #76 

Linking against "onecore_apiset" will mean the code will run on whichever version of the Windows SDK is being used, but maybe not different versions if the API set host changes. In practice, the ETW functions are all in kernelbase.dll and don't jump around to different hosts, so this will just link directly against kernelbase.dll and skip all the forwarding.

### CODE REVIEW

File: etw/rust/tracelogging/src/native.rs [hunk 1]
```diff
@@ -444,6 +445,7 @@ extern "system" {
         outer_context: usize,
         reg_handle: &mut u64,
     ) -> u32;
+
```
Comment (Robo210) [inline etw/rust/tracelogging/src/native.rs:448]: Where did this blank line come from?

Meh. It can be removed later if anybody wants to.

**Review by idigdoug — APPROVED** [review]
