### PR TITLE
Fix: TraceLoggingDynamic.h failing under /Zc:preprocessor on msvc

### LINKED ISSUE #79: TraceLoggingDynamic.h is not MSVC conformant preprocessor compliant
Including TraceLoggingDynamic.h on msvc when /Zc:preprocessor is specified results in compile errors, as  _tld_ASSERT relies on non-conformant behavior. In particular, the behavior of L##str and L#exp are non-conformant (https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview?view=msvc-170#lval).
As well as the handling of the "tuple-like" ```(__annotation(...), DbgRaiseAssertionFailure(), 0)``` part, which it somehow decides is a valid expression evaluating to zero.

An alternative formulation which satisfies both, assuming C++11 is acceptable, is 
```cpp
#define _tld_ASSERT(exp, str) ((void)(!(exp) ? []()  { __annotation(L"Debug", L"AssertFail", L"TraceLogging: " #exp L" : " #str); DbgRaiseAssertionFailure(); return 0; }() : 0))
```

Compiler explorer link demonstrating the msvc preprocessor behavior:
https://godbolt.org/z/T8K1sjefT

I'll put up a Pull Request in a few minutes.

### PR DESCRIPTION
**Pull request by cgettys-microsoft**
* Replace the non-conformant ```L#exp``` and ```L##str``` with ```#exp``` and ```#str```, since there is already a proceeding string literal that they will be combined with; per https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview?view=msvc-170#lval, as well as via [Compiler Explorer](https://godbolt.org/z/T8K1sjefT) , this should compile with both the old and new preprocessor (as well as being more compatible with clang, gcc, and so on.
* ~~Also replace the parentheses shenanigans (that really shouldn't compile!) with immediately evaluated Lambda shenanigans that are conformant preprocessor compatible. I'm assuming TraceLoggingDynamic.h already requires C++11, but if it doesn't, we could make TLD_DEBUG default to 0 for pre-C++11 compiler versions.~~

Closes #79

### CODE REVIEW

File: etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h [hunk 1]
```diff
@@ -632,7 +632,10 @@ namespace tld
 
 #ifndef _tld_ASSERT
   #if TLD_DEBUG
-    #define _tld_ASSERT(exp, str) ((void)(!(exp) ? (__annotation(L"Debug", L"AssertFail", L"TraceLogging: " L#exp L" : " L##str), DbgRaiseAssertionFailure(), 0) : 0))
+    // The below lambda should compile on both msvc's older preprocessor (i.e. /Zc:preprocessor-) and also msvc's modern preprocessor (/Zc:preprocessor)
+    // However, it does require at least C++11 support due to the use of lambdas. 
+    // If you need to support pre-C++11 compilers, you'll need to #define TLD_DEBUG 0 or #define _tld_ASSERT to something else before including this header.
```
Comment (Robo210) [inline etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: Does this change where the PDB is associated to in the PDB? Can you provide a sample before and after from pdbdump to confirm?

Comment (cgettys-microsoft) [reply etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: Let me dig up a copy of pdbdump. I'm 99% sure it does based on the identical location of the label (just before the __int2c / int 44 instruction) in Compiler Explorer:
old:
```
# License: MSVC Proprietary
# The use of this compiler is only permitted for internal evaluation purposes and is otherwise governed by the MSVC License Agreement.
# See https://visualstudio.microsoft.com/license-terms/vs2022-ga-community/
tv71 = 0
void testFunc(void) PROC                             ; testFunc
$LN6:
        sub     rsp, 24
        xor     eax, eax
        cmp     eax, 1
        je      SHORT $LN3@testFunc
__annotation$5:
        int     44                                        ; 0000002cH
        mov     DWORD PTR tv71[rsp], 0
        jmp     SHORT $LN4@testFunc
$LN3@testFunc:
        mov     DWORD PTR tv71[rsp], 0
$LN4@testFunc:
        add     rsp, 24
        ret     0
void testFunc(void) ENDP                             ; testFunc
```
New:
```
# License: MSVC Proprietary
# The use of this compiler is only permitted for internal evaluation purposes and is otherwise governed by the MSVC License Agreement.
# See https://visualstudio.microsoft.com/license-terms/vs2022-ga-community/
$T1 = 32
tv71 = 36
void testFunc(void) PROC                             ; testFunc
$LN5:
        push    rdi
        sub     rsp, 48                             ; 00000030H
        xor     eax, eax
        cmp     eax, 1
        je      SHORT $LN3@testFunc
        lea     rax, QWORD PTR $T1[rsp]
        mov     rdi, rax
        xor     eax, eax
        mov     ecx, 1
        rep stosb
        lea     rcx, QWORD PTR $T1[rsp]
        call    <lambda_604973acf1d06f3ef6d60e520864562e>::operator()(void)const  ; <lambda_604973acf1d06f3ef6d60e520864562e>::operator()
        mov     DWORD PTR tv71[rsp], eax
        jmp     SHORT $LN4@testFunc
$LN3@testFunc:
        mov     DWORD PTR tv71[rsp], 0
$LN4@testFunc:
        add     rsp, 48                             ; 00000030H
        pop     rdi
        ret     0
void testFunc(void) ENDP                             ; testFunc

this$ = 8
<lambda_604973acf1d06f3ef6d60e520864562e>::operator()(void)const  PROC ; <lambda_604973acf1d06f3ef6d60e520864562e>::operator()
        mov     QWORD PTR [rsp+8], rcx
__annotation$3:
        int     44                                        ; 0000002cH
        xor     eax, eax
        ret     0
<lambda_604973acf1d06f3ef6d60e520864562e>::operator()(void)const  ENDP ; <lambda_604973acf1d06f3ef6d60e520864562e>::operator()
```
However... the O0 codegen for the lambda is worse.

Comment (cgettys-microsoft) [reply etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: @jaykrell pointed out that the Lambda was unnecessary (I tried that first, but I must have had a typo I caught later that I thought was responsible).

I've pushed another iteration that keeps it as a ternary - the only change is now the token pasting, so it should not make any difference from a codegen perspective.

Comment (cgettys-microsoft) [reply etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: Just in case there was doubt:
https://godbolt.org/z/Trebb7ccq

I don't remember the incantation to list annotations via pdbdump, I could diff the binaries but given that even the labels are identically named and only preprocessor side stuff has changed, I'm assuming that's sufficient.

Comment (Robo210) [reply etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: It's fine now. I'm just waiting for Doug to chime in.

File: etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h [hunk 2]
```diff
@@ -632,7 +632,7 @@ namespace tld
 
 #ifndef _tld_ASSERT
   #if TLD_DEBUG
-    #define _tld_ASSERT(exp, str) ((void)(!(exp) ? (__annotation(L"Debug", L"AssertFail", L"TraceLogging: " L#exp L" : " L##str), DbgRaiseAssertionFailure(), 0) : 0))
+    #define _tld_ASSERT(exp, str) ((void)(!(exp) ? (__annotation(L"Debug", L"AssertFail", L"TraceLogging: " #exp L" : " #str), DbgRaiseAssertionFailure(), 0) : 0))
```
Comment (cgettys-microsoft) [inline etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: I'm not sure which widening trick is most portable outside msvc.
https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview?view=msvc-170#lval
suggests something like 3 options.
```
#define WIDE(str) L##str
#define STRING2(str) WIDE(#str)
```
Might be more robust than this to older compilers? but I'm not sure how much of a concern that is given the current non-conformance of the header.

Comment (cgettys-microsoft) [reply etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: Happy to use a different one if you have preferences.

Comment (idigdoug) [inline etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: Removing the `L` seems reasonable. Why did we also change the str from "prefix with L" to "convert to string"?

**Review by idigdoug — CHANGES_REQUESTED** [review]
Unless there was a reason to change the behavior, please change `#str` to `str` to preserve existing behavior.

Comparable code in TraceLoggingProvider.h looks like this:

```
  #define _tlg_ASSERT(exp, str) ((void)(!(exp) ? (__annotation(L"Debug", L"AssertFail", L"TraceLogging: " _tlg_LSTRINGIZE(exp) L" : " str), TLG_RAISEASSERTIONFAILURE(), 0) : 0))
```

File: etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h (hunk 2 above)
Comment (cgettys-microsoft) [reply etw/cpp/traceloggingdynamic/TraceLoggingDynamic.h]: tl;dr: because I screwed up. 

I'll be honest, I'm not a macro or preprocessor wizard. I'm just tilting at windmills over here experimenting with seeing if we could maybe possibly get a large, 1st party codebase (*cough* SQL *cough*) to use header units instead of PCH, so that we can enter this decade.

So human error on my part. I saw many, many places where macros like ```L##x``` were not playing nice because the old preprocessor was happy to pretend they actually just were ```L x```.
Some of those also had evaluation order shenanigans going on... sometimes it seems like the old preprocessor likes to treat
```
`MY_MACRO((X))
```
As if it was:
```
#define DEFER(...) __VA_ARGS__
MY_MACRO(DEFER(X))
```
Though I could be wrong about that, I've spent the last two days traipsing my way through ~300 files full of particularly cursed macros.

And I hadn't had any problems with TraceLoggingProvider.h, so I hadn't spotted the similarity.

**Comment by cgettys-microsoft** [comment]
> Unless there was a reason to change the behavior, please change `#str` to `str` to preserve existing behavior.
> 
> Comparable code in TraceLoggingProvider.h looks like this:
> 
> ```
>   #define _tlg_ASSERT(exp, str) ((void)(!(exp) ? (__annotation(L"Debug", L"AssertFail", L"TraceLogging: " _tlg_LSTRINGIZE(exp) L" : " str), TLG_RAISEASSERTIONFAILURE(), 0) : 0))
> ```
Done, good catch.

An aside on TraceLoggingProvider.h - it's probably academic (since I assume that's usually only ever compiled with gcc and clang and the like, and I also assume the macros in question don't expect to be passed zero varadiac arguments. But the old msvc preprocessor is lax about comma elision around variadic arguments - other compilers will only elide ```, ## __VA_ARGS__``` to nothing if there are no variadic arguments, but the old msvc preprocessor would also elide ```, __VA_ARGS__```:
https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview?view=msvc-170#comma-elision-in-variadic-macros

Thought I'd mention it just in case.

**Review by idigdoug — APPROVED** [review]

**Review by Robo210 — APPROVED** [review]
